# Generated by Django 3.2.8 on 2021-11-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sscapital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prometheus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.FloatField()),
                ('value', models.FloatField()),
                ('returns', models.FloatField()),
            ],
        ),
    ]
