# Generated by Django 3.2.8 on 2021-11-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sscapital', '0002_prometheus'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials',
            name='returns',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
