# Generated by Django 3.2.8 on 2021-11-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sscapital', '0003_financials_returns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financials',
            name='capital_invested',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='financials',
            name='market_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='financials',
            name='returns',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='financials',
            name='shareholder',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='money_moved',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='prometheus',
            name='capital',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='prometheus',
            name='returns',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='prometheus',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
