name: Google Cloud Run Deployment

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: heptra-capital

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        export_default_credentials: true
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    # Build the Docker image
    - name: Build & Publish
      run: |
        gcloud config set project $PROJECT_NAME
        gcloud builds submit --tag gcr.io/${{ secrets.RUN_PROJECT }}/$PROJECT_NAME
        gcloud config set run/region us-central1
      
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud run deploy $PROJECT_NAME --image gcr.io/${{ secrets.RUN_PROJECT }}/$PROJECT_NAME \
        --platform managed \
        --allow-unauthenticated \
        --memory 512M